<a href="https://colab.research.google.com/github/snipe02/DESENVOLVIMENTO-ORIENTADO-A-TESTES/blob/main/numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np


#DATASET SIMPLES QUE SIMULA A QUANTIDADE DE VENDAS DE AUTOMÓVEIS EM CADA TRIMESTRE DURANTE TRÊS ANO(DE 2019 A 2021)
dados = np.array([[2019, 1, 5000],
                  [2019, 2, 7000],
                  [2019, 3, 8000],
                  [2019, 4, 10000],
                  [2020, 1, 9000],
                  [2020, 2, 11000],
                  [2020, 3, 12000],
                  [2020, 4, 15000],
                  [2021, 1, 12000],
                  [2021, 2, 15000],
                  [2021, 3, 17000],
                  [2021, 4, 20000]])

print(dados.shape)   #FORMA DO CONJUNTO DE DADOS(mostra quantidade de linhas e colunas)

print(dados[4, 0])   #ACESSANDO POR INDEXAÇÃO O ANO DE 2020 DO 1º TRIMESTRE.

print(dados[10, 2])  #ACESSANDO POR INDEXAÇÃO O VALOR DE VENDAS FEITO NO 3º TRIMESTRE DO ANO DE 2021.

dados2020 = dados[dados[:, 0] == 2021]  #FATIAMOS AQUI TODOS OS DADOS REFERENTES AO ANO DE 2021. (ano, trimestre e total de vendas.)

print(dados2020)


trimestre1 = dados[:, 2][dados[:, 1] == 1] # AQUI BUSQUEI O TOTAL DE VENDAS, MAS APENAS DO 1º SEMESTRE DE CADA ANO.
media_trimestre1 = np.mean(trimestre1) #AQUI EU USO UMA FUNÇÃO ESTÁTISTICA PARA ME RETORNAR A MÉDIA VENDIDA NO 1ºSEMESTRE DE CADA ANO.
print(media_trimestre1) 

total_vendas = dados[:, 2]
soma_vendas = np.sum(total_vendas)
print(soma_vendas)













(12, 3)
2020
17000
[[ 2021     1 12000]
 [ 2021     2 15000]
 [ 2021     3 17000]
 [ 2021     4 20000]]
8666.666666666666
141000
